services:
  backend:
    build:
      context: ./backend
    networks:
      - dev

  nginx:
    build:
      context: .
      dockerfile: Dockerfile.nginx
    ports:
      - "80:80"
    depends_on:
      - backend
    networks:
      - dev

networks:
  dev:
