version: "3.8"

networks:
  dev:

services:
  frontend:
    build:
      context: ./frontend
    ports:
      - "80:80"
    networks:
      - dev
    depends_on:
      - backend

  backend:
    build:
      context: ./backend
    ports:
      - "5000:5000"
    networks:
      - dev
